/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: giacomoalbani (https://sketchfab.com/giacomoalbani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/8-oxygen-f0a87eabf23d4453b6c2117a734a5bce
Title: 8 - Oxygen
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Oxygen(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/oxygen.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["CINEMA_4D_Principale"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="10Neonfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="CINEMA_4D_Editor"
                  position={[70.066, 165.959, -607.856]}
                  rotation={[-Math.PI, -1.448, 2.922]}
                >
                  <group name="Object_5" />
                </group>
                <group name="CerchioG" rotation={[0, 0, 0.8]}>
                  <group name="BOIII" rotation={[0, 0, -0.8]}>
                    <group name="Elettroni">
                      <group name="E1___INTERNI" rotation={[0, 0.19, 0]}>
                        <group
                          name="Orbita_1"
                          rotation={[-3.141, 1.308, -1.701]}
                        >
                          <mesh
                            name="Orbita_1_Nuovo_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Orbita_1_Nuovo_0.geometry}
                            material={materials.Nuovo}
                          />
                          <group
                            name="Gruppo_Elettroni_1"
                            rotation={[0, 0, -1.344]}
                          >
                            <group name="Sfera_1_0" position={[0, 120, 0]}>
                              <mesh
                                name="Sfera_1_0_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_0_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_1"
                              position={[0, -120, 0]}
                              rotation={[0, 0, Math.PI]}
                            >
                              <mesh
                                name="Sfera_1_1_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_1_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                      <group name="E2" rotation={[-2.39, 0.027, -0.981]}>
                        <group name="Orbita_2" rotation={[0, 0, -1.357]}>
                          <mesh
                            name="Orbita_2_Nuovo_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.Orbita_2_Nuovo_0.geometry}
                            material={materials.Nuovo}
                          />
                          <group name="Gruppo_Elettroni_2">
                            <group name="Sfera_1_0_2" position={[0, 160, 0]}>
                              <mesh
                                name="Sfera_1_0_2_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_0_2_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_1_2"
                              position={[113.137, 113.137, 0]}
                              rotation={[0, 0, -Math.PI / 4]}
                            >
                              <mesh
                                name="Sfera_1_1_2_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_1_2_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_2"
                              position={[160, 0, 0]}
                              rotation={[0, 0, -Math.PI / 2]}
                            >
                              <mesh
                                name="Sfera_1_2_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_2_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_3"
                              position={[113.137, -113.137, 0]}
                              rotation={[0, 0, -2.356]}
                            >
                              <mesh
                                name="Sfera_1_3_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_3_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_4"
                              position={[0, -160, 0]}
                              rotation={[0, 0, -Math.PI]}
                            >
                              <mesh
                                name="Sfera_1_4_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_4_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_5"
                              position={[-113.137, -113.137, 0]}
                              rotation={[0, 0, 2.356]}
                            >
                              <mesh
                                name="Sfera_1_5_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_5_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_6"
                              position={[-160, 0, 0]}
                              rotation={[0, 0, Math.PI / 2]}
                            >
                              <mesh
                                name="Sfera_1_6_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_6_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                            <group
                              name="Sfera_1_7"
                              position={[-113.137, 113.137, 0]}
                              rotation={[0, 0, Math.PI / 4]}
                            >
                              <mesh
                                name="Sfera_1_7_Nuovo3_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Sfera_1_7_Nuovo3_0.geometry}
                                material={materials["Nuovo.3"]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                      <group name="E3" rotation={[0, 0.19, 0]}>
                        <group
                          name="Orbita_3"
                          rotation={[-0.09, 1.282, -2.627]}
                        >
                          <group
                            name="Gruppo_Elettroni_3"
                            rotation={[0, 0, 1.344]}
                          />
                        </group>
                      </group>
                      <group name="E4" rotation={[0, 0.19, 0]}>
                        <group name="Orbita_4" rotation={[-0.329, 0, 0.099]}>
                          <group
                            name="Gruppo_Elettroni_4"
                            rotation={[0, 0, -1.344]}
                          />
                        </group>
                      </group>
                      <group name="E5" rotation={[0.721, 0.349, -0.128]}>
                        <group name="Orbita_4_2" rotation={[-0.329, 0, 0.099]}>
                          <group
                            name="Gruppo_Elettroni_4_2"
                            rotation={[0, 0, -1.344]}
                          />
                        </group>
                      </group>
                      <group name="E6" rotation={[1.645, 0.037, 0.189]}>
                        <group name="Orbita_4_3" rotation={[-0.329, 0, 0.099]}>
                          <group
                            name="Gruppo_Elettroni_4_3"
                            rotation={[0, 0, -1.344]}
                          />
                        </group>
                      </group>
                      <group
                        name="E7___ESTERNI"
                        rotation={[-0.369, 0.02, 0.069]}
                      >
                        <group name="Orbita_4_4" rotation={[-0.329, 0, 0.099]}>
                          <group
                            name="Gruppo_Elettroni_4_4"
                            rotation={[0, 0, -1.344]}
                          />
                        </group>
                      </group>
                    </group>
                    <group name="Forza" rotation={[0, 0, -0.182]}>
                      <group name="Nucleo" rotation={[-1.299, -0.739, 3.039]}>
                        <group name="Protoni" rotation={[0, 0, 2.124]}>
                          <group
                            name="Sfera_1_0_3"
                            position={[-9.615, 6.366, -15.252]}
                            rotation={[0, 0.012, 0.001]}
                          >
                            <mesh
                              name="Sfera_1_0_3_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_0_3_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_1_3"
                            position={[-18.936, 5.553, 11.882]}
                            rotation={[-0.008, 0.003, -0.648]}
                          >
                            <mesh
                              name="Sfera_1_1_3_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_1_3_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_2_2"
                            position={[2.071, 12.974, -6.506]}
                            rotation={[0.012, -0.004, -1.249]}
                          >
                            <mesh
                              name="Sfera_1_2_2_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_2_2_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_3_2"
                            position={[-3.237, -5.963, -7.242]}
                            rotation={[0.016, -0.003, -1.862]}
                          >
                            <mesh
                              name="Sfera_1_3_2_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_3_2_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_4_2"
                            position={[9.944, 0.314, -0.624]}
                            rotation={[0.018, 0.038, -2.5]}
                          >
                            <mesh
                              name="Sfera_1_4_2_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_4_2_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_5_2"
                            position={[6.465, 2.005, -17.199]}
                            rotation={[-0.006, 0.011, 3.137]}
                          >
                            <mesh
                              name="Sfera_1_5_2_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_5_2_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_6_2"
                            position={[21.447, 0.293, -11.778]}
                            rotation={[0.022, 0, 2.542]}
                          >
                            <mesh
                              name="Sfera_1_6_2_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_6_2_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_7_2"
                            position={[1.861, -19.389, -0.124]}
                            rotation={[-0.002, 0.005, 1.895]}
                          >
                            <mesh
                              name="Sfera_1_7_2_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_7_2_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_8"
                            position={[4.954, -8.842, 11.54]}
                            rotation={[-0.001, -0.005, 1.262]}
                          >
                            <mesh
                              name="Sfera_1_8_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_8_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_9"
                            position={[-4.487, 4.14, 5.145]}
                            rotation={[-0.03, -0.003, 0.652]}
                          >
                            <mesh
                              name="Sfera_1_9_Nuovo1_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_9_Nuovo1_0.geometry}
                              material={materials["Nuovo.1"]}
                            />
                          </group>
                        </group>
                        <group name="Neutroni" rotation={[0, 0, 2.124]}>
                          <group
                            name="Sfera_1_0_4"
                            position={[-7.211, -2.215, 19.593]}
                            rotation={[-0.012, 0.001, -0.001]}
                          >
                            <mesh
                              name="Sfera_1_0_4_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_0_4_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_1_4"
                            position={[-10.099, -10.81, 6.403]}
                            rotation={[-0.633, 0.01, 0.001]}
                          >
                            <mesh
                              name="Sfera_1_1_4_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_1_4_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_2_3"
                            position={[-17.585, -0.208, -3.009]}
                            rotation={[-1.258, 0.003, 0.007]}
                          >
                            <mesh
                              name="Sfera_1_2_3_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_2_3_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_3_3"
                            position={[-16.093, -15.457, -7.711]}
                            rotation={[-1.886, -0.009, 0.004]}
                          >
                            <mesh
                              name="Sfera_1_3_3_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_3_3_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_4_3"
                            position={[11.178, -11.975, -10.837]}
                            rotation={[-2.507, -0.002, -0.013]}
                          >
                            <mesh
                              name="Sfera_1_4_3_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_4_3_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_5_3"
                            position={[18.256, -12.736, 3.515]}
                            rotation={[3.131, 0.003, -0.007]}
                          >
                            <mesh
                              name="Sfera_1_5_3_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_5_3_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_6_3"
                            position={[15.293, 15.125, 2.293]}
                            rotation={[2.518, 0.006, -0.013]}
                          >
                            <mesh
                              name="Sfera_1_6_3_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_6_3_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_7_3"
                            position={[8.6, 6.558, 14.07]}
                            rotation={[1.884, -0.003, 0]}
                          >
                            <mesh
                              name="Sfera_1_7_3_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_7_3_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_8_2"
                            position={[0.449, 19.06, 8.23]}
                            rotation={[1.249, -0.006, -0.005]}
                          >
                            <mesh
                              name="Sfera_1_8_2_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_8_2_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                          <group
                            name="Sfera_1_9_2"
                            position={[-13.255, 15.209, -2.391]}
                            rotation={[0.626, -0.006, -0.002]}
                          >
                            <mesh
                              name="Sfera_1_9_2_Nuovo2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.Sfera_1_9_2_Nuovo2_0.geometry}
                              material={materials["Nuovo.2"]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/oxygen.glb");



